import express from 'express';
import { randomUUID, timingSafeEqual } from 'node:crypto';
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/streamableHttp.js';
import { z } from 'zod';

const PORT=8787;
const ROOT='/var/lib/playable-cave-mcp';
const SESSION_ROOT=path.join(ROOT,'sessions');
const ACTIVE_SESSION_FILE=path.join(ROOT,'active-session.json');
const TOKEN_FILE='/etc/playable-cave-mcp.token';
await fsp.mkdir(SESSION_ROOT,{recursive:true});
let MCP_TOKEN='';
try{MCP_TOKEN=(await fsp.readFile(TOKEN_FILE,'utf8')).trim()}catch{}
if(!MCP_TOKEN){console.error('Missing '+TOKEN_FILE);process.exit(1)}

const app=express();
app.disable('x-powered-by');
app.use(express.json({limit:'64mb'}));

function safeId(v){return String(v||'').replace(/[^A-Za-z0-9_.:-]/g,'_').slice(0,160)}
function sessionDir(id){return path.join(SESSION_ROOT,safeId(id))}
async function readJson(p,fb=null){try{return JSON.parse(await fsp.readFile(p,'utf8'))}catch{return fb}}
async function writeJson(p,v){await fsp.mkdir(path.dirname(p),{recursive:true});await fsp.writeFile(p,JSON.stringify(v,null,2))}
function mimeExt(m=''){m=m.toLowerCase();if(m.includes('png'))return 'png';if(m.includes('jpeg')||m.includes('jpg'))return 'jpg';if(m.includes('webp'))return 'webp';if(m.includes('gif'))return 'gif';return 'bin'}
function parseDataUrl(s){const m=/^data:([^;,]+)(?:;[^,]*)?;base64,([A-Za-z0-9+/=\r\n]+)$/i.exec(String(s||''));if(!m)throw new Error('Expected base64 data URL');return {mime:m[1].toLowerCase(),bytes:Buffer.from(m[2].replace(/\s+/g,''),'base64')}}
function dims(buf,mime){try{if(mime==='image/png'&&buf.length>=24&&buf.subarray(1,4).toString()==='PNG')return {width:buf.readUInt32BE(16),height:buf.readUInt32BE(20)};if(/jpe?g/.test(mime)){let i=2;while(i+9<buf.length){if(buf[i]!==0xff){i++;continue}const marker=buf[i+1],len=buf.readUInt16BE(i+2);if([0xc0,0xc1,0xc2,0xc3,0xc5,0xc6,0xc7,0xc9,0xca,0xcb,0xcd,0xce,0xcf].includes(marker))return {height:buf.readUInt16BE(i+5),width:buf.readUInt16BE(i+7)};i+=2+len}}}catch{}return {width:0,height:0}}
function bearer(req){const h=String(req.headers.authorization||'');return h.startsWith('Bearer ')?h.slice(7):''}
function tokenOk(got){const a=Buffer.from(String(got||'')),b=Buffer.from(MCP_TOKEN);return a.length===b.length&&timingSafeEqual(a,b)}
function mcpAuth(req,res,next){if(!tokenOk(bearer(req)))return res.status(401).json({error:'unauthorized'});next()}
async function loadSession(id){const d=sessionDir(id),meta=await readJson(path.join(d,'session.json'));if(!meta)throw new Error('Session not found');return {d,meta}}
async function saveSession(d,meta){meta.updated_at=new Date().toISOString();await writeJson(path.join(d,'session.json'),meta)}
async function listAssetMeta(d){const dir=path.join(d,'assets');let names=[];try{names=await fsp.readdir(dir)}catch{}const out=[];for(const n of names){if(n.endsWith('.json')){const x=await readJson(path.join(dir,n));if(x)out.push(x)}}return out.sort((a,b)=>(a.index??99999)-(b.index??99999))}
async function assetRecord(sessionId,assetId){const {d,meta}=await loadSession(sessionId),id=safeId(assetId),a=await readJson(path.join(d,'assets',id+'.json'));if(!a)throw new Error('Asset not found');return {d,meta,a,id}}
function browserSessionAuth(req,res,next){const sid=safeId(req.params.sessionId||req.body?.session_id);const key=String(req.headers['x-playable-session-key']||'');if(!sid||!key)return res.status(401).json({error:'session auth required'});readJson(path.join(sessionDir(sid),'session.json')).then(meta=>{if(!meta||key!==meta.browser_key)return res.status(401).json({error:'bad session key'});req.pcSession=meta;next()});}

app.get('/health',(req,res)=>res.json({ok:true,name:'Playable Cave MCP',version:'0.2.0'}));
app.get('/api/active-session',async(req,res)=>{const active=await readJson(ACTIVE_SESSION_FILE,null);if(!active)return res.status(404).json({error:'no active session'});res.json(active)});

// Browser bridge: create a random workspace session.
app.post('/api/session',async(req,res)=>{try{const id='pc_'+randomUUID().replace(/-/g,'').slice(0,20),browser_key=randomUUID()+randomUUID();const d=sessionDir(id);await fsp.mkdir(path.join(d,'assets'),{recursive:true});const mcp_key=randomUUID()+randomUUID();const meta={session_id:id,browser_key,mcp_key,name:String(req.body?.name||'Playable session').slice(0,160),source:String(req.body?.source||'browser'),created_at:new Date().toISOString(),updated_at:new Date().toISOString(),revision:0,status:'active'};await saveSession(d,meta);await writeJson(ACTIVE_SESSION_FILE,{session_id:id,mcp_key,name:meta.name,updated_at:meta.updated_at});res.json({session_id:id,browser_key,mcp_key})}catch(e){res.status(500).json({error:String(e.message||e)})}});

app.post('/api/session/:sessionId/asset',browserSessionAuth,async(req,res)=>{try{const {d,meta}=await loadSession(req.params.sessionId),assetId=safeId(req.body?.asset_id||('asset_'+req.body?.index));if(!assetId)throw new Error('asset_id required');const p=parseDataUrl(req.body?.data_url),dm=dims(p.bytes,p.mime),adir=path.join(d,'assets');await fsp.mkdir(adir,{recursive:true});const original=path.join(adir,assetId+'.original.'+mimeExt(p.mime)),current=path.join(adir,assetId+'.current.'+mimeExt(p.mime));if(!fs.existsSync(original))await fsp.writeFile(original,p.bytes);await fsp.writeFile(current,p.bytes);const old=await readJson(path.join(adir,assetId+'.json'),{});const a={...old,asset_id:assetId,index:Number(req.body?.index??old.index??-1),name:String(req.body?.name||old.name||assetId),mime:p.mime,width:Number(req.body?.width||dm.width||0),height:Number(req.body?.height||dm.height||0),detected_width:dm.width,detected_height:dm.height,kind:String(req.body?.kind||old.kind||'image'),stable_key:String(req.body?.stable_key||old.stable_key||''),luna_id:String(req.body?.luna_id||old.luna_id||''),source_path:String(req.body?.source_path||old.source_path||''),revision:Number(old.revision||0),pending_revision:Number(old.pending_revision||0),status:'synced',updated_at:new Date().toISOString(),current_file:path.basename(current),original_file:path.basename(original)};await writeJson(path.join(adir,assetId+'.json'),a);meta.revision++;await saveSession(d,meta);res.json({ok:true,asset:a})}catch(e){res.status(400).json({error:String(e.message||e)})}});

app.get('/api/session/:sessionId/changes',browserSessionAuth,async(req,res)=>{try{const {d,meta}=await loadSession(req.params.sessionId),assets=await listAssetMeta(d);res.json({session_id:meta.session_id,revision:meta.revision,changes:assets.filter(a=>a.status==='pending'),assets:assets.map(a=>({asset_id:a.asset_id,revision:a.revision,pending_revision:a.pending_revision,status:a.status}))})}catch(e){res.status(400).json({error:String(e.message||e)})}});

app.get('/api/session/:sessionId/replacement/:assetId',browserSessionAuth,async(req,res)=>{try{const {d,a,id}=await assetRecord(req.params.sessionId,req.params.assetId);if(a.status!=='pending'||!a.pending_file)return res.status(404).json({error:'no pending replacement'});const b=await fsp.readFile(path.join(d,'assets',a.pending_file));res.json({asset_id:id,revision:a.pending_revision,mime:a.pending_mime||a.mime,data_url:`data:${a.pending_mime||a.mime};base64,${b.toString('base64')}`,original_width:a.width,original_height:a.height,pending_width:a.pending_width,pending_height:a.pending_height,prompt:a.pending_prompt||''})}catch(e){res.status(400).json({error:String(e.message||e)})}});

app.post('/api/session/:sessionId/applied/:assetId',browserSessionAuth,async(req,res)=>{try{const {d,meta,a,id}=await assetRecord(req.params.sessionId,req.params.assetId);if(a.status==='pending'&&a.pending_file){const src=path.join(d,'assets',a.pending_file),dst=path.join(d,'assets',id+'.current.'+mimeExt(a.pending_mime||a.mime));await fsp.copyFile(src,dst);a.current_file=path.basename(dst);a.mime=a.pending_mime||a.mime;a.revision=a.pending_revision||a.revision+1;a.status='applied';a.applied_at=new Date().toISOString();delete a.pending_file;await writeJson(path.join(d,'assets',id+'.json'),a);meta.revision++;await saveSession(d,meta)}res.json({ok:true,asset:a})}catch(e){res.status(400).json({error:String(e.message||e)})}});

async function mcpSession(session_id,session_key){if(!session_id){const active=await readJson(ACTIVE_SESSION_FILE,null);if(!active)throw new Error('No active playable session');session_id=active.session_id;session_key=active.mcp_key}const x=await loadSession(session_id);if(!session_key||String(session_key)!==String(x.meta.mcp_key||''))throw new Error('Invalid session key');return x}

function makeServer(){
  const mcp=new McpServer({name:'playable-cave-pro',version:'0.2.0'},{capabilities:{tools:{}}});
  const txt=o=>({content:[{type:'text',text:typeof o==='string'?o:JSON.stringify(o,null,2)}]});
  mcp.registerTool('connection_status',{title:'Playable Cave Connection Status',description:'Check that the Playable Cave MCP bridge is online. No playable data is returned.',inputSchema:{}},async()=>txt({ok:true,name:'Playable Cave MCP',version:'0.2.0',auth:'session capability key'}));
  mcp.registerTool('list_assets',{title:'List Playable Assets',description:'List assets in a Playable Cave session with stable IDs, sizes and Luna/path identity.',inputSchema:{session_id:z.string(),session_key:z.string()}},async({session_id,session_key})=>{const {d,meta}=await mcpSession(session_id,session_key),assets=await listAssetMeta(d);return txt({session:{session_id:meta.session_id,name:meta.name,revision:meta.revision},assets:assets.map(a=>({asset_id:a.asset_id,index:a.index,name:a.name,mime:a.mime,width:a.width,height:a.height,kind:a.kind,stable_key:a.stable_key,luna_id:a.luna_id,source_path:a.source_path,revision:a.revision,status:a.status}))})});
  mcp.registerTool('get_asset',{title:'Get Playable Asset',description:'Fetch one asset as an image plus exact Playable Cave metadata. Use before editing so canvas size and identity can be preserved.',inputSchema:{session_id:z.string(),session_key:z.string(),asset_id:z.string()}},async({session_id,session_key,asset_id})=>{await mcpSession(session_id,session_key);const {d,a}=await assetRecord(session_id,asset_id),file=a.current_file||a.original_file,b=await fsp.readFile(path.join(d,'assets',file));return {content:[{type:'text',text:JSON.stringify({asset_id:a.asset_id,name:a.name,mime:a.mime,width:a.width,height:a.height,luna_id:a.luna_id,source_path:a.source_path,stable_key:a.stable_key,revision:a.revision},null,2)},{type:'image',data:b.toString('base64'),mimeType:a.mime}]}});
  mcp.registerTool('replace_asset',{title:'Stage AI Asset Replacement',description:'Stage an edited PNG/JPEG for a Playable Cave asset. Playable Cave will apply it through its safe replacement engine; original Luna ID/path is never changed.',inputSchema:{session_id:z.string(),session_key:z.string(),asset_id:z.string(),image_base64:z.string().min(20),mime_type:z.string().optional(),prompt:z.string().optional(),expected_revision:z.number().int().optional()}},async({session_id,session_key,asset_id,image_base64,mime_type,prompt,expected_revision})=>{await mcpSession(session_id,session_key);const {d,meta,a,id}=await assetRecord(session_id,asset_id);if(expected_revision!=null&&expected_revision!==a.revision)throw new Error(`Revision conflict: expected ${expected_revision}, current ${a.revision}`);const mime=String(mime_type||a.mime||'image/png').toLowerCase();if(!/^image\/(png|jpeg|jpg|webp)$/.test(mime))throw new Error('Only PNG/JPEG/WebP replacements are allowed');const b=Buffer.from(image_base64.replace(/^data:[^,]+,/,'').replace(/\s+/g,''),'base64');if(!b.length)throw new Error('Empty image');const dm=dims(b,mime),rev=(a.revision||0)+1,fn=id+'.pending.r'+rev+'.'+mimeExt(mime);await fsp.writeFile(path.join(d,'assets',fn),b);a.pending_file=fn;a.pending_mime=mime;a.pending_width=dm.width;a.pending_height=dm.height;a.pending_revision=rev;a.pending_prompt=String(prompt||'');a.status='pending';a.updated_at=new Date().toISOString();await writeJson(path.join(d,'assets',id+'.json'),a);meta.revision++;await saveSession(d,meta);return txt({ok:true,asset_id:id,pending_revision:rev,original_canvas:{width:a.width,height:a.height},generated_canvas:dm,normalization_required:!!(a.width&&a.height&&dm.width&&dm.height&&(a.width!==dm.width||a.height!==dm.height)),message:'Replacement staged. Playable Cave will normalize/apply it while preserving stable ID, Luna ID/path and canvas constraints.'})});
  mcp.registerTool('restore_asset',{title:'Restore Original Asset',description:'Stage the original asset as a replacement, allowing Playable Cave to restore it safely.',inputSchema:{session_id:z.string(),session_key:z.string(),asset_id:z.string()}},async({session_id,session_key,asset_id})=>{await mcpSession(session_id,session_key);const {d,meta,a,id}=await assetRecord(session_id,asset_id),b=await fsp.readFile(path.join(d,'assets',a.original_file)),rev=(a.revision||0)+1,fn=id+'.pending.r'+rev+'.'+mimeExt(a.mime);await fsp.writeFile(path.join(d,'assets',fn),b);a.pending_file=fn;a.pending_mime=a.mime;a.pending_width=a.width;a.pending_height=a.height;a.pending_revision=rev;a.pending_prompt='restore original';a.status='pending';await writeJson(path.join(d,'assets',id+'.json'),a);meta.revision++;await saveSession(d,meta);return txt({ok:true,asset_id:id,pending_revision:rev,message:'Original staged for safe restore in Playable Cave.'})});
  mcp.registerTool('validate_session',{title:'Validate Playable Asset Session',description:'Check session asset metadata for identity/canvas problems before applying AI edits.',inputSchema:{session_id:z.string(),session_key:z.string()}},async({session_id,session_key})=>{const {d,meta}=await mcpSession(session_id,session_key),assets=await listAssetMeta(d),issues=[];for(const a of assets){if(/^data:/i.test(a.luna_id||''))issues.push(`${a.asset_id}: Luna ID corrupted`);if(a.pending_width&&a.width&&a.pending_width!==a.width)issues.push(`${a.asset_id}: pending width ${a.pending_width} differs from ${a.width}`);if(a.pending_height&&a.height&&a.pending_height!==a.height)issues.push(`${a.asset_id}: pending height ${a.pending_height} differs from ${a.height}`)}return txt({session_id:meta.session_id,assets:assets.length,pending:assets.filter(a=>a.status==='pending').length,issues,ok:issues.length===0})});
  return mcp;
}

app.all('/mcp',async(req,res)=>{let transport;try{const mcp=makeServer();transport=new StreamableHTTPServerTransport({sessionIdGenerator:undefined});await mcp.connect(transport);await transport.handleRequest(req,res,req.body)}catch(e){console.error(e);if(!res.headersSent)res.status(500).json({error:'MCP server error'})}});

app.use((err,req,res,next)=>{console.error(err);if(!res.headersSent)res.status(500).json({error:'server error'})});
app.listen(PORT,'127.0.0.1',()=>console.log(`Playable Cave MCP listening on 127.0.0.1:${PORT}`));
